### PR TITLE
Remove active record dependency

### PR DESCRIPTION
**Pull request by knapo**

### CODE REVIEW

**Comment by theSteveMitchell** [comment]
This doesn't remove anything, rather it's adding a Mongoid dependency.  Is that what you intended?

**Comment by theSteveMitchell** [comment]
I'm going to reopen with a rebase in #17

**Comment by theSteveMitchell** [comment]
Sorry, ignore the reference from #16.

**Comment by theSteveMitchell** [comment]
Oh, goodness.  Ignore my first comment also... I see you're adding both active record and mongoid as development dependencies only.

**Comment by knapo** [comment]
Yeap, it's necessary. I don't have and don't want ActiveRecord and it's installed together with after_party gem.

**Comment by theSteveMitchell** [comment]
Thanks @knapo!  Bumped to version 1.8

**Pull request merged**
