### PR TITLE
Multiple task with same name bug

### PR DESCRIPTION
**Pull request by mamidinilesh**
Having multiple task with same name, created at different time, produces a bug.
It creates multiple entries of version in task_recorder. they above code will check, whether similar file exists or not

### CODE REVIEW

**Comment by theSteveMitchell** [comment]
@mamidinilesh would you mind elaborating a little more on the bug you're seeing?  Do you mean to say that rake after_party:status lists the same job twice?

**Comment by manuca** [comment]
Hey @theSteveMitchell I've just seen this happen to me version (1.11.2)

To reproduce you need to generate 2 tasks with the same name. I did the first one months ago, ran it and all went well back then. Months later I needed a similar task, and gave it the same name (accidentally). When I `rake after_part:run` the last task it re-ran the previous version although there was an entry in the `task_records` table (from months ago). 

Final outcome in the `task_records` table is the inclusion of 3 timestamps: the first one, a duplicate of the first one, and the new one.

**Comment by theSteveMitchell** [comment]
@manuca Thanks for the details. I'll merge once we can get a passing CI

**Comment by theSteveMitchell** [comment]
merged to #71 and fixed lint errors there.

**Pull request closed without merging**
